import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// @ts-ignore
import TronWeb from 'tronweb'
import { useState } from 'react'

const Home: NextPage = () => {
    const tronWeb = new TronWeb({
        fullHost: 'https://api.shasta.trongrid.io',
        headers: { 'TRON-PRO-API-KEY': process.env.API_KEY },
        privateKey: process.env.PRIVATE_KEY,
    })
    
    
    async function send_token(to_add: string, amount: string): Promise<string> {
        console.log(await tronWeb.isConnected())
        const contract = await tronWeb.contract().at(process.env.TOKEN_ADDRESS)
        const transaction = await contract.transfer(to_add, parseInt(amount)).send()
        console.log(transaction)
        return transaction
    }

    // send_token('TFmV2WPBznHr6LSsxHyAF1PNsjSFRF1DtP', '10')
    //send_token('TXVFSvRd6aMmDUddRo43GKiK7C2rHdAqNo', '10')
    const [inputValue, setInputValue] = useState(''); // ''

    const send =  () => {
        console.log(inputValue)
        const tx =  send_token(inputValue, '1').then(tx => tx)
        alert(`transaction hash: ${tx}`)
    }


    // todo - add a button to send tokens
    // todo - add link to the scan : https://shasta.tronscan.org/#/transaction/${transaction_hash}

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing <code className={styles.code}>pages/index.tsx</code>
                </p>


                <input 
                type="text"
                placeholder="wallet address"
                    value={ inputValue }
                    onChange={ e =>  setInputValue( e.target.value ) }
                />

                <button onClick={send}> SEND </button>

                
            </main>

            <footer className={styles.footer}>
                
            </footer>
        </div>
    )
}

export default Home
