import type { NextPage } from 'next'
import { useState, useCallback } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    // window.open(`https://shasta.tronscan.org/#/transaction/${res}`);

    const [walletAddress, setWalletAddress] = useState('')

    const handleChange = useCallback(async () => {
        const res = await fetch(`/api/address/${walletAddress}`)
        const tx = await res.text()
        console.log(tx)
        window.open(`https://shasta.tronscan.org/#/transaction/${tx}`)
    }, [walletAddress])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <input
                    type="text"
                    placeholder="Enter wallet address"
                    value={walletAddress}
                    onChange={e => setWalletAddress(e.target.value)}
                />
                <button style={{ marginTop: 10 }} onClick={handleChange}>
                    Enviar
                </button>
            </main>
            <footer className={styles.footer}></footer>
        </div>
    )
}

export default Home
